/* automatically generated by rust-bindgen 0.72.1 */

#[cfg(target_family = "windows")]
#[allow(non_camel_case_types)]
pub type char_t = std::primitive::u16;

#[cfg(not(target_family = "windows"))]
#[allow(non_camel_case_types)]
pub type char_t = std::primitive::u8;

pub const UNMANAGEDCALLERSONLY_METHOD : *const char_t = usize::MAX as *const char_t;

// Signature of delegate returned by coreclr_delegate_type::load_assembly_and_get_function_pointer
type LoadAssemblyAndGetFunctionPointerArgs = 
	(
		*const char_t,                    /*assembly_path      Fully qualified path to assembly. */
        *const char_t,                    /*type_name          Assembly qualified type name. */
        *const char_t,                    /*method_name        Public static method name compatible with delegateType. */
        *const char_t,                    /*delegate_type_name Assembly qualified delegate type name or null.
                                                        	   or UNMANAGEDCALLERSONLY_METHOD if the method is marked with
                                                        	   the UnmanagedCallersOnlyAttribute. */
        *mut ::std::os::raw::c_void,      /* reserved Extensibility parameter (currently unused and must be 0). */
        *mut *mut ::std::os::raw::c_void, /* delegate Pointer where to store the function pointer result). */
    );


pub type LoadAssemblyAndGetFunctionPointerFn = 
	unsafe extern "system" fn(
        assembly_path: *const char_t,
        type_name: *const char_t,
        method_name: *const char_t,
        delegate_type_name: *const char_t,
        reserved: *mut ::std::os::raw::c_void,
        delegate: *mut *mut ::std::os::raw::c_void,
    ) -> i32;

// Signature of delegate returned by load_assembly_and_get_function_pointer_fn when delegate_type_name == null (default)
pub type ComponentEntryPointFn = 
	unsafe extern "system" fn(
        arg: *mut ::std::os::raw::c_void,
        arg_size_in_bytes: i32,
    ) -> i32;

pub type GetFunctionPointerFn = 
	unsafe extern "system" fn(
        type_name: *const char_t,                   /* Assembly qualified type name */
        method_name: *const char_t,                 /* Public static method name compatible with delegateType */
        delegate_type_name: *const char_t,          /* Assembly qualified delegate type name or null,
                                        			   or UNMANAGEDCALLERSONLY_METHOD if the method is marked with
                                        			   the UnmanagedCallersOnlyAttribute. */
        load_context: *mut ::std::os::raw::c_void,  /* Extensibility parameter (currently unused and must be 0) */
        reserved: *mut ::std::os::raw::c_void,      /* Extensibility parameter (currently unused and must be 0) */
        delegate: *mut *mut ::std::os::raw::c_void, /* Pointer where to store the function pointer result */
    ) -> i32;

pub type LoadAssemblyFn =
    unsafe extern "system" fn(
        assembly_path: *const char_t,              /* Fully qualified path to assembly */
        load_context: *mut ::std::os::raw::c_void, /* Extensibility parameter (currently unused and must be 0) */
        reserved: *mut ::std::os::raw::c_void,     /* Extensibility parameter (currently unused and must be 0) */
    ) -> i32;

pub type LoadAssemblyBytesFn =
	unsafe extern "system" fn(
        assembly_bytes: *const ::std::os::raw::c_void, /* Bytes of the assembly to load */
        assembly_bytes_len: usize,                     /* Byte length of the assembly to load */
        symbols_bytes: *const ::std::os::raw::c_void,  /* Optional. Bytes of the symbols for the assembly */
        symbols_bytes_len: usize,                      /* Optional. Byte length of the symbols for the assembly */
        load_context: *mut ::std::os::raw::c_void,     /* Extensibility parameter (currently unused and must be 0) */
        reserved: *mut ::std::os::raw::c_void,         /* Extensibility parameter (currently unused and must be 0) */
    ) -> i32;
