/* automatically generated by rust-bindgen 0.72.1 */

#[cfg(target_family = "windows")]
#[allow(non_camel_case_types)]
pub type char_t = std::primitive::u16;

#[cfg(not(target_family = "windows"))]
#[allow(non_camel_case_types)]
pub type char_t = std::primitive::u8;

#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}

// Parameters for get_hostfxr_path
//
// Fields:
//   size
//     Size of the struct. This is used for versioning.
//
//   assembly_path
//     Path to the component's assembly.
//     If specified, hostfxr is located as if the assembly_path is the apphost
//
//   dotnet_root
//     Path to directory containing the dotnet executable.
//     If specified, hostfxr is located as if an application is started using
//     'dotnet app.dll', which means it will be searched for under the dotnet_root
//     path and the assembly_path is ignored.
//
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct get_hostfxr_parameters {
    pub size: usize,
    pub assembly_path: *const char_t,
    pub dotnet_root: *const char_t,
}

//
// Get the path to the hostfxr library
//
// Parameters:
//   buffer
//     Buffer that will be populated with the hostfxr path, including a null terminator.
//
//   buffer_size
//     [in] Size of buffer in char_t units.
//     [out] Size of buffer used in char_t units. If the input value is too small
//           or buffer is nullptr, this is populated with the minimum required size
//           in char_t units for a buffer to hold the hostfxr path
//
//   get_hostfxr_parameters
//     Optional. Parameters that modify the behaviour for locating the hostfxr library.
//     If nullptr, hostfxr is located using the environment variable or global registration
//
// Return value:
//   0 on success, otherwise failure
//   0x80008098 - buffer is too small (HostApiBufferTooSmall)
//
// Remarks:
//   The full search for the hostfxr library is done on every call. To minimize the need
//   to call this function multiple times, pass a large buffer (e.g. PATH_MAX).
//
#[link(name = "nethost")]
unsafe extern "C" {
    pub unsafe fn get_hostfxr_path(
        buffer: *mut char_t,
        buffer_size: *mut usize,
        parameters: *const get_hostfxr_parameters,
    ) -> ::std::os::raw::c_int;
}
